plugins {
    id "java-library"
    id "info.solidsoft.pitest"
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

dependencies {
    implementation project(":konveyor")
    implementation libs.dagger
    implementation libs.javax.inject

    annotationProcessor libs.dagger.compiler
    testAnnotationProcessor libs.dagger.compiler

    implementation "org.boofcv:boofcv-core:1.2.0"
    implementation "org.boofcv:boofcv-io:1.2.0"
    implementation "com.google.zxing:core:3.5.1"
    implementation "org.json:json:20240303"

    testImplementation testFixtures(project(":konveyor"))
    testImplementation libs.junit.jupiter
    testImplementation libs.mockito.core
}

java {
    withSourcesJar()
    withJavadocJar()
}

test {
    useJUnitPlatform {
        if (!project.hasProperty("runIntegration")) {
            excludeTags "integration"
        }
    }
}

pitest {
    junit5PluginVersion = "1.2.1"
    mutators = ["ALL"]
    targetClasses = ["hu.kdea.szavazas.**.*Service"]
    targetTests = ["hu.kdea.szavazas.**.*Test"]
    excludedTestClasses = ["hu.kdea.szavazas.FullPipelineTest"]
    excludedGroups = ["integration"]
    outputFormats = ["HTML", "XML"]
    threads = 4
    timestampedReports = false
}
